### ISSUE TITLE
Support for IPv6 mapped IPv4 addresses

### ISSUE THREAD

**Issue by ilkkao** [indutny/node-ip#28]
Ip module doesn't seem to support IPv6 addresses that contain mapped IPv4 address? This is odd as in dual-stack case that's what methods from net module return.

```
      "Error: Invalid ip address: ::ffff:201.51.40.12",
      "    at Error (native)",
      "    at Object.toBuffer (/home/mas/mas/node_modules/ip/lib/ip.js:38:40)",
      "    at Object.isEqual (/home/mas/mas/node_modules/ip/lib/ip.js:229:10)"
```

**Comment by ilkkao** [comment]
Checked that `::FFFF:x.y.z.w` really is a valid presentation of IPv6 address. Mentioned here: https://tools.ietf.org/html/rfc4038#section-4.2

I might want to add support myself, but can't promise anything.

My understanding is that both `isEqual("::ffff:201.51.40.12", "::ffff:201.51.40.12")` and `isEqual("::ffff:201.51.40.12", "201.51.40.12")` should return true.

**Comment by ilkkao** [comment]
This shouldn't be hard as`isEqual("::ffff:c933:280c", "201.51.40.12")` already returns true.

**Comment by ilkkao** [comment]
PR about this is already open, somehow I missed it. Continuing there.
