### ISSUE TITLE
Bash on Windows networkinterface error

### ISSUE THREAD

**Issue by zukoaang** [indutny/node-ip#62]
Crashes on Bash on Windows with the following error:

```
/home/ohad/projects/Coindash/node_modules/ip/lib/ip.js:353
  var interfaces = os.networkInterfaces();
                      ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.ip.address (/home/ohad/projects/Coindash/node_modules/ip/lib/ip.js:353:23)
    at Object.appStarted (/home/ohad/projects/Coindash/server/logger.js:30:41)
    at Server.app.listen (/home/ohad/projects/Coindash/server/index.js:41:12)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1278:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! coindash@0.0.1 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
```
Should be a very simple fix, as seen here: indexzero/node-portfinder#42

**Comment by miladmostavi** [comment]
The issue has been tagged as `fixinbound` by BashOnWindows team: https://github.com/Microsoft/BashOnWindows/issues/468

Until the fix is released to windows, you can use this fork of node-ip: https://github.com/miladmostavi/node-ip/commit/432dd36500ccac6f07ac920752b533ad27e63d38
